//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstateApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RealEstateApp.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate column name found:.
        /// </summary>
        internal static string errorColumnNamesAreTheSame {
            get {
                return ResourceManager.GetString("errorColumnNamesAreTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column name or number of supplied values does not match table definition..
        /// </summary>
        internal static string errorDifferentCountOfColumnsAndValues {
            get {
                return ResourceManager.GetString("errorDifferentCountOfColumnsAndValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such type in the database called.
        /// </summary>
        internal static string errorNoSuchType {
            get {
                return ResourceManager.GetString("errorNoSuchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified table does not exist:.
        /// </summary>
        internal static string errorTableNotExists {
            get {
                return ResourceManager.GetString("errorTableNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already the same table in the database:.
        /// </summary>
        internal static string errorTableWithSameNameExists {
            get {
                return ResourceManager.GetString("errorTableWithSameNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All tables:.
        /// </summary>
        internal static string textAllTables {
            get {
                return ResourceManager.GetString("textAllTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the command to start.
        /// </summary>
        internal static string textEnterCommand {
            get {
                return ResourceManager.GetString("textEnterCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome, let&apos;s get started!.
        /// </summary>
        internal static string textWelcome {
            get {
                return ResourceManager.GetString("textWelcome", resourceCulture);
            }
        }
    }
}
